// Generated by CoffeeScript 1.7.1
(function() {
  var $, ASYNC, KEY, P, TRM, alert, badge, debug, echo, help, indexes, info, log, new_db, options, rainbow, rpr, urge, warn, whisper;

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'HOLLERITH/main';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  urge = TRM.get_logger('urge', badge);

  echo = TRM.echo.bind(TRM);

  rainbow = TRM.rainbow.bind(TRM);

  options = require('../options');

  indexes = options['data']['indexes'];

  new_db = require('level');

  ASYNC = require('async');

  P = require('pipedreams');

  $ = P.$.bind(P);

  KEY = require('./KEY');

  if (module.parent == null) {
    urge('HOLLERITH');
  }

}).call(this);
