// Generated by CoffeeScript 1.7.1
(function() {
  var BNP, DIFF, KEY, M, T, TEXT, TRM, TYPES, alert, badge, debug, echo, eq, eqs, help, info, log, neq, njs_fs, options, rainbow, rpr, urge, warn, whisper;

  njs_fs = require('fs');

  TYPES = require('coffeenode-types');

  TEXT = require('coffeenode-text');

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'HOLLERITH/test';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  urge = TRM.get_logger('urge', badge);

  echo = TRM.echo.bind(TRM);

  rainbow = TRM.rainbow.bind(TRM);

  options = require('../options');

  M = options['marks'];

  BNP = require('coffeenode-bitsnpieces');

  eq = BNP.equals.bind(BNP);

  neq = function(a, b) {
    return !eq(a, b);
  };

  KEY = require('./scratch/KEY');

  DIFF = require('coffeenode-diff');

  eqs = function(probe, setpoint) {
    if (eq(probe, setpoint)) {
      return;
    }
    return log(DIFF.colorize(probe, setpoint));
  };

  T = function(title, method) {
    var arity, fail_mark, pass_mark, title_txt, width, _;
    arity = method.length;
    if (!((1 <= arity && arity <= 2))) {
      throw new Error("expected test method with 1 or 2 arguments, got method with " + arity + " arguments");
    }
    width = 30;
    title_txt = TEXT.truncate(title);
    title_txt = TEXT.flush_left(title_txt, width);
    pass_mark = '◌';
    fail_mark = '▼';
    _ = {
      eqs: function(probe, setpoint) {
        if (eq(probe, setpoint)) {
          return log(TRM.GREEN(pass_mark, title_txt, TRM.grey(setpoint)));
        } else {
          return log(TRM.RED(fail_mark, title_txt), DIFF.colorize(probe, setpoint));
        }
      },
      eqjson: function(probe, setpoint) {
        if (eq(probe, setpoint)) {
          return log(TRM.GREEN(pass_mark, title_txt, TRM.grey(JSON.stringify(setpoint))));
        } else {
          return log(TRM.RED(fail_mark, title_txt), DIFF.colorize(JSON.stringify(probe), JSON.stringify(setpoint)));
        }
      }
    };
    return method(_);
  };

  T('KEY.new_node 1', function(_) {
    return _.eqs(KEY.new_node('myrealm', 'mytype', 'myid'), '$.|myrealm/mytype/myid|');
  });

  T('KEY.new_node 2', function(_) {
    return _.eqs(KEY.new_node('myrealm', 'mytype', 'myid', 'tail1', 'tail2'), '$.|myrealm/mytype/myid/tail1/tail2|');
  });

  T('KEY.new_facet', function(_) {
    return _.eqs(KEY.new_facet('gtfs', 'stop', '5643', 'name', 'Piazza Bavaria'), '$:|gtfs/stop/5643|name|Piazza Bavaria|0|');
  });

  T('KEY.new_secondary_facet', function(_) {
    return _.eqs(KEY.new_secondary_facet('gtfs', 'stop', '5643', 'name', 'Piazza Bavaria'), '%:|gtfs/stop|name|Piazza Bavaria|5643|0|');
  });

  T('KEY.new_link', function(_) {
    return _.eqs(KEY.new_link('gtfs', 'stoptime', '77876452', 'gtfs', 'stop', '3221'), '$^|gtfs/stoptime/77876452|gtfs/stop/3221|0|');
  });

  T('KEY.new_secondary_link', function(_) {
    return _.eqs(KEY.new_secondary_link('gtfs', 'stoptime', '77876452', 'gtfs', 'stop', '3221'), '%^|gtfs/stoptime|gtfs/stop/3221|77876452|0|');
  });

  T('KEY.read node 1', function(_) {
    return _.eqjson(KEY.read('$.|myrealm/mytype/myid|'), {
      "level": "primary",
      "type": "node",
      "id": "myrealm/mytype/myid",
      "key": "$.|myrealm/mytype/myid|"
    });
  });

  T('KEY.read node 2', function(_) {
    return _.eqjson(KEY.read('$.|myrealm/mytype/myid/tail1/tail2|'), {
      "level": "primary",
      "type": "node",
      "id": "myrealm/mytype/myid/tail1/tail2",
      "key": "$.|myrealm/mytype/myid/tail1/tail2|"
    });
  });

  T('KEY.read facet', function(_) {
    return _.eqjson(KEY.read('$:|gtfs/stop/5643|name|Piazza Bavaria|0|'), {
      "level": "primary",
      "type": "facet",
      "id": "gtfs/stop/5643",
      "name": "name",
      "value": "Piazza Bavaria",
      "distance": 0,
      "key": "$:|gtfs/stop/5643|name|Piazza Bavaria|0|"
    });
  });

  T('KEY.read secondary facet', function(_) {
    return _.eqjson(KEY.read('%:|gtfs/stop|name|Piazza Bavaria|5643|0|'), {
      "level": "secondary",
      "type": "facet",
      "id": "gtfs/stop/5643",
      "name": "name",
      "value": "Piazza Bavaria",
      "distance": 0,
      "key": "%:|gtfs/stop|name|Piazza Bavaria|5643|0|"
    });
  });

  T('KEY.read link', function(_) {
    return _.eqjson(KEY.read('$^|gtfs/stoptime/77876452|gtfs/stop/3221|0|'), {
      "level": "primary",
      "type": "link",
      "id": "gtfs/stoptime/77876452",
      "target": "gtfs/stop/3221",
      "distance": 0,
      "key": "$^|gtfs/stoptime/77876452|gtfs/stop/3221|0|"
    });
  });

  T('KEY.read secondary link', function(_) {
    return _.eqjson(KEY.read('%^|gtfs/stoptime|gtfs/stop/3221|77876452|0|'), {
      "level": "secondary",
      "type": "link",
      "id": "gtfs/stoptime/77876452",
      "target": "gtfs/stop/3221",
      "distance": 0,
      "key": "%^|gtfs/stoptime|gtfs/stop/3221|77876452|0|"
    });
  });

}).call(this);
